/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.mixologyinventory;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Scanner;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Insets;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class App extends Application{
    public static void main(String[] args){
        Application.launch(args);
    }
    
    @Override
    public void start(Stage primaryStage) throws URISyntaxException, IOException{
        Parent root = FXMLLoader.load(getClass().getResource("mix.fxml"));
        Scene scene = new Scene(root);
        primaryStage.setTitle("Mixology With Prices");
        
        
        primaryStage.setResizable(false);
        primaryStage.setScene(scene);
        primaryStage.show();    
    }
    
    public static Ingredient[] ingredientsListFromConfig(String configFilePath) throws FileNotFoundException{
        ArrayList<String> ingredientsTypeList = new ArrayList<String>();
        File configFile = new File(configFilePath);
        Scanner configInput = new Scanner(configFile);
        while(configInput.hasNextLine()){
            String ingredientTypeLine = configInput.nextLine();
            if (!ingredientTypeLine.isEmpty()){
                ingredientsTypeList.add(ingredientTypeLine.trim());
            }
        }
        Ingredient[] ingredientsTypeArray = new Ingredient[ingredientsTypeList.size()];
        for (int i = 0; i<ingredientsTypeArray.length; i++){
            ingredientsTypeArray[i]= new Ingredient(ingredientsTypeList.get(i));
        }
        return ingredientsTypeArray;
    }
    

}
